INSERT INTO director (director_id, director_name, director_image_url, is_deleted, created_at,
                      updated_at)
VALUES (1, '감독01', 'https://example.com/images/director-01.jpg', FALSE, NOW(), NOW()),
       (2, '감독02', 'https://example.com/images/director-02.jpg', FALSE, NOW(), NOW()),
       (3, '감독03', 'https://example.com/images/director-03.jpg', FALSE, NOW(), NOW()),
       (4, '감독04', 'https://example.com/images/director-04.jpg', FALSE, NOW(), NOW()),
       (5, '감독05', 'https://example.com/images/director-05.jpg', FALSE, NOW(), NOW()),
       (6, '감독06', 'https://example.com/images/director-06.jpg', FALSE, NOW(), NOW()),
       (7, '감독07', 'https://example.com/images/director-07.jpg', FALSE, NOW(), NOW()),
       (8, '감독08', 'https://example.com/images/director-08.jpg', FALSE, NOW(), NOW()),
       (9, '감독09', 'https://example.com/images/director-09.jpg', FALSE, NOW(), NOW()),
       (10, '감독10', 'https://example.com/images/director-10.jpg', FALSE, NOW(), NOW()),
       (11, '감독11', 'https://example.com/images/director-11.jpg', FALSE, NOW(), NOW()),
       (12, '감독12', 'https://example.com/images/director-12.jpg', FALSE, NOW(), NOW()),
       (13, '감독13', 'https://example.com/images/director-13.jpg', FALSE, NOW(), NOW()),
       (14, '감독14', 'https://example.com/images/director-14.jpg', FALSE, NOW(), NOW()),
       (15, '감독15', 'https://example.com/images/director-15.jpg', FALSE, NOW(), NOW()),
       (16, '감독16', 'https://example.com/images/director-16.jpg', FALSE, NOW(), NOW()),
       (17, '감독17', 'https://example.com/images/director-17.jpg', FALSE, NOW(), NOW()),
       (18, '감독18', 'https://example.com/images/director-18.jpg', FALSE, NOW(), NOW()),
       (19, '감독19', 'https://example.com/images/director-19.jpg', FALSE, NOW(), NOW()),
       (20, '감독20', 'https://example.com/images/director-20.jpg', FALSE, NOW(), NOW()),
       (21, '감독21', 'https://example.com/images/director-21.jpg', FALSE, NOW(), NOW()),
       (22, '감독22', 'https://example.com/images/director-22.jpg', FALSE, NOW(), NOW()),
       (23, '감독23', 'https://example.com/images/director-23.jpg', FALSE, NOW(), NOW()),
       (24, '감독24', 'https://example.com/images/director-24.jpg', FALSE, NOW(), NOW()),
       (25, '감독25', 'https://example.com/images/director-25.jpg', FALSE, NOW(), NOW()),
       (26, '감독26', 'https://example.com/images/director-26.jpg', FALSE, NOW(), NOW()),
       (27, '감독27', 'https://example.com/images/director-27.jpg', FALSE, NOW(), NOW()),
       (28, '감독28', 'https://example.com/images/director-28.jpg', FALSE, NOW(), NOW()),
       (29, '감독29', 'https://example.com/images/director-29.jpg', FALSE, NOW(), NOW()),
       (30, '감독30', 'https://example.com/images/director-30.jpg', FALSE, NOW(), NOW());